### ISSUE TITLE
Implementation of Audio wave

### ISSUE THREAD

**Issue by ayzerobug** [ihsanberahim/livespeechtotext-for-flutter#1]
I'll like to use audio visualisation with the package but I'm not seeing a documentation regarding that

**Comment by ihsanberahim** [comment]
Are you looking to display an animated visualization of the audio recording?

**Comment by ihsanberahim** [comment]
Will check if the very high request for this.

**Comment by ihsanberahim** [comment]
Will check if the very high request for this.

**Comment by ahmetveysels** [comment]
it is a necessary need. Thank you
