### ISSUE TITLE
Setting the compileSdkVersion 31 conflicts with other packages.

### ISSUE THREAD

**Issue by norman17uy** [ihsanberahim/livespeechtotext-for-flutter#3]
Hi @ihsanberahim , your package is fantastic!

According to your documentation, it's recommended to set the following:

MinSDK to 21
CompileSDK to 31

However, configuring it this way conflicts with other packages that rely on a more recent compileSdkVersion. Are there any solutions or workarounds for this issue?

![Screenshot 2023-09-23 at 9 54 51 AM](https://github.com/ihsanberahim/livespeechtotext-for-flutter/assets/100858019/68393a23-92b0-464a-baaa-c8ad5799ca74)

**Comment by ihsanberahim** [comment]
You can use higher SDK if you need. Minimum SDK means lowest SDK not the recommended one. Actually higher is better.
