### ISSUE TITLE
Support other languages like Persian?

### ISSUE THREAD

**Issue by AliEasy** [ihsanberahim/livespeechtotext-for-flutter#4]

**Comment by ihsanberahim** [comment]
Persian looks like not currently supported yet. Based on these

ios 
- https://developer.apple.com/documentation/speech/sfspeechrecognizer/1649889-supportedlocales
- https://www.apple.com/ios/feature-availability/#quicktype-keyboard-dictation

android 
- https://cloud.google.com/speech-to-text/docs/speech-to-text-supported-languages
